default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: tutorial
  password: tutorial
  database: tutorial_development
  host: 127.0.0.1

development:
  <<: *default
  database: tutorial_development

test:
  <<: *default
  database: tutorial_test

production:
  <<: *default
  database: db/production.sqlite3

migrate_development:
  <<: *default
  adapter: mysql2
  database: tutorial

migrate_test:
  <<: *default
  database: tutorial_test
